// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4UmUtWAJkgl2ufVSaFthL_-XVgZQvNzA',
    appId: '1:50863428326:web:4929bceb7bd6caacae2127',
    messagingSenderId: '50863428326',
    projectId: 'assessment-3-73a09',
    authDomain: 'assessment-3-73a09.firebaseapp.com',
    storageBucket: 'assessment-3-73a09.appspot.com',
    measurementId: 'G-3HJFK2ZJ14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSctQ6eGOaAYWYELEfQfsnFBsYPQvXhzw',
    appId: '1:50863428326:android:812f87d04a82c589ae2127',
    messagingSenderId: '50863428326',
    projectId: 'assessment-3-73a09',
    storageBucket: 'assessment-3-73a09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZzbHMOzXRUTo0BfVz1C-MxY8lrvSfow',
    appId: '1:50863428326:ios:d7f2b5e3d6ce204bae2127',
    messagingSenderId: '50863428326',
    projectId: 'assessment-3-73a09',
    storageBucket: 'assessment-3-73a09.appspot.com',
    iosBundleId: 'com.example.assessment3',
  );
}
